#!/bin/bash
notify-send -i display "Display profile" "$AUTORANDR_CURRENT_PROFILE"
# feh --bg-fill /usr/share/backgrounds/gnome/rapha-desktop-aw15-b.jpg
echo "Test run autorandr `date`"  >> ~/Documents/autorandr-test.txt
feh --bg-fill /home/eoin/Dropbox/Pictures/Wallpapers/active/dracula.png
